spring.application.name=mcpclientapp

logging.pattern.console=%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n
spring.ai.openai.api=${OPENAI_API_KEY}
logging.level.org.springframework.ai.chat.client.advisor=DEBUG


spring.ai.mcp.client.stdio.servers-configuration=classpath:mcp-servers.json
#spring.ai.mcp.client.streamable-http.connections.eazybytes.url=http://localhost:8090
#spring.ai.mcp.client.streamable-http.connections.eazybytes.endpoint=/mcp