spring.application.name=openai
logging.pattern.console=%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n
spring.ai.openai.api=${OPENAI_API_KEY}
logging.level.org.springframework.ai.chat.client.advisor=DEBUG


spring.datasource.url=jdbc:h2:file:~/study/spring-ai/openai/src/main/resources;AUTO_SERVER=true
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=rohan
spring.datasource.password=12345

spring.ai.chat.memory.repository.jdbc.initialize-schema=always
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update

spring.ai.vectorstore.qdrant.initialize-schema=true
spring.ai.vectorstore.qdrant.host=localhost
spring.ai.vectorstore.qdrant.port=6334
spring.ai.vectorstore.qdrant.collection-name=test-data

audit.token-usage.enabled=true